/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blah_Test */

#ifndef _Included_blah_Test
#define _Included_blah_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blah_Test
 * Method:    sup
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_blah_Test_sup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
